name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check Java version
      run: java -version

    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: 11


      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install SonarScanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        export PATH=$PATH:/path/to/sonar-scanner-4.6.2.2472-linux/bin
        
    - name: Run SonarScanner
      run: |
        ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
          -Dsonar.projectKey=test1000_test \
          -Dsonar.sources=src \
          -Dsonar.tests=tests \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=test1000 \
          -Dsonar.login=f7701a68ec2edfae4443ac10ed7632579c49e4ed # replace with your SonarCloud token
